package com.azmqalabs.edaattestautomation.objectrepository;

public class EdaatOR {

//Biller Module
	// Login Page for All
	public final static String LoginPage_Username = "//input[@name='UserName']";
	public final static String LoginPage_Password = "//input[@name='Password']";
	public final static String LoginPage_LogIn = "//button[@id='btnlogin']";
	public final static String LoginPage_Invalid_LogIn = "//span[text()='Invalid username or password']";
	public final static String LoginPage_send = "//button[@id='btnSendRequest']";
	public final static String LoginPage_confirmation = "//label[@id='Message' and contains(text(),'please check your email and reset the password.')]";
	
	public final static String LoginPage_Changelanguage = "//li[@class='nav-item d-none d-lg-flex ml-2']//a[text()='EN']";
	public final static String Logout = "(//a[text()='Logout'])[1]";
	public final static String LoginPage_Error ="//span[@style='display: block;' and text()='Invalid username or password']";
	public final static String LoginPage_Error_Invalid ="//span[@style='display: block;' and text()='Your account needs to be activated']";
	public final static String LoginPage_Forgetlink = "//a[text()='Forgot password?']";
	// Biller Home page
	public final static String Biller_HomePage_Main = "//h6[text()='Main Page']";
	public final static String Biller_Link = "//a[text()='Biller Login']";
	// Biller Add Individual Client Page
	public final static String Biller_Client = "//a[@id='lnkMyClients2']";
	public final static String Biller_Corporate = "//h6[text()='Corporate Info']";
	public final static String Systemmgmt_Menu = "//a[@id='lnkSystemMangement2']";
	public final static String Systemmgmt_NotApproved_Menu = "//a[@id='lnkUnderApprovedBillerList2']";
	public final static String Systemmgmt_NotApproved_Edit= "//td[9]";
	public final static String Systemmgmt_Approved_Menu = "//a[@id='lnkApprovedBillerList2']";
	public final static String Systemmgmt_InvoiceTemplate = "//a[@id=\"lnkInvoiceSetting2\"]";
	
	public final static String Systemmgmt_table = "//table[@id='dtBasicExample']";
	public final static String Systemmgmt_table_approved = "//table[@id='dtApprovedBillers']";
	public final static String Systemmgmt_table_Invoice = "//div[@id=\"DataTables_Table_0_wrapper\"]";
	public final static String Systemmgmt_toggle = "//input[@id='1']";
	public final static String Admin_SystemMgm_BillerActivateButton="(//a[contains(@href,'BillerActivation')])";
	
	public final static String Biller_Add_Individualclient = "//a[@id='lnkCustomerList2']";
	public final static String Biller_Add_client = "//a[@id='lnkCustomerList2']";
	public final static String Biller_Add_Companyclient = "//a[@id='lnkCompanyList2']";
	public final static String Biller_Sub_Individualclient = "//a[@id='lnkSubBillers2']";
	public final static String Biller_Sub_IndividualsubBiller = "//a[@id='lnkSubBillersIndividualList2']";
	public final static String Biller_Settings = "//a[@id='lnkMySettings']";
	public final static String Biller_Individualclient_sname = "//input[@id='SecondName']";
	public final static String Biller_Add_Individualclient_Button = "//button[@id='btnAddCustomer']";
	public final static String Biller_Add_Invoice_Button = "//button[@id='btnAddTemplate']";
	public final static String Biller_Add_Prod_Buttonbtn="//[button[@id='AddProduct']";
	public final static String Biller_Add_Invoice_template = "//a[@id='lnkInvoiceSetting2']";
	public final static String Biller_Add_Product = "//a[text()='Products Management']";
	public final static String Biller_Invoice_TemplateArabic = "//input[@id='NameAr']";
	public final static String Biller_Prod_NameArabic = "(//input[@id='Name'])[2]";
	public final static String Biller_Invoice_TemplateEng= "//input[@id='NameEn']";
	public final static String Biller_Prod_Price= "//input[@id='Price']";
	public final static String Biller_Prod_Addbutton="//button[@id='btnAddProduct']";
	public final static String Biller_Individualclient_fname = "//input[@id='FirstName']";
	public final static String Biller_Individualclient_Cname = "//input[@id='Name']";
	public final static String Biller_Maxlimit = "//input[@id='Limit']";
	public final static String Biller_TransferDuration = "//input[@id='TransferDuration']";
	public final static String Biller_AzimFee = "//input[@id='AzimFee']";
	public final static String Biller_sadadFee = "//input[@id='sadadFee']";
	public final static String Biller_BillerAliasNameEn = "//input[@id='BillerAliasNameEn']";
	public final static String Biller_MaximumInvoiceAmount = "//input[@id='MaximumInvoiceAmount']";
	public final static String Biller_Imgdownload = "//a[@class='text-white']";
	public final static String Biller_InvoiceName= "(//tr[2]|//td[2])[1]";
	public final static String Biller_Invoice_TemplateDisc= "//textarea[@name='Description']";
	public final static String Biller_Invoice_TemplateRefcode= "//input[@class='form-control animated fadeIn']";
	public final static String Biller_Invoice_Templateactideacti= "//input[@class='switch']";
	public final static String Biller_Invoice_TemplateBillpay= "(//input[@type='checkbox'])[5]";
	public final static String Biller_Invoice_TemplateVeriable= "(//input[@type='checkbox'])[8]";

	
	public final static String Biller_Individualclient_tname = "//input[@id='ThirdName']";
	public final static String Biller_Individualclient_lname = "//input[@id='LastName']";
	public final static String Biller_Individualclient_IdNumber = "//input[@id='IdNumber']";
	public final static String Biller_Subbiller_NId="//input[@id='NationalId']";
	public final static String Biller_Individualclient_Name = "//input[@id='Name']";
	public final static String Biller_Individualclient_CustomerRefNumber = "//input[@id='CustomerRefNumber']";
	public final static String Biller_Individualclient_DateOfBirth = "//input[@id='DateOfBirth']";
	public final static String Biller_Invoice_Templatetype_Rec= "//input[@id='BillType_16']";
	public final static String Biller_Invoice_Templatetype_Chkboxes= "//div[@class='form-group mb-4']/div//input[@type='checkbox']";
	public final static String Biller_Individualclient_refno = "//input[@name='CustomerRefNumber']";
	public final static String Biller_Individualclient_togle ="//label[@for='status']";
	
	public final static String Biller_Invoice_Select="(//select[@id='ServiceId'])[2]";
	public final static String Biller_Individualclient_DateOfYear = "//select[@title='Change the year']";
	public final static String Biller_Individualclient_DateOfMonth = "//select[@title='Change the month']";
	public final static String Biller_Individualclient_MobileNo = "//input[@id='MobileNo']";
	public final static String Biller_Individualclient_Add = "//input[@type='submit']";
	public final static String Biller_Invoice_Add = "//button[@id='btnAdd']";
	public final static String Biller_Save = "//input[@id='btnSave']";
	public final static String Biller_Save_Yes = "//button[@id='btnConfirmSaveBillerInfo']";
	public final static String Biller_Save_Yesclose = "//button[@id='btnCloseSendInformationToChecker']";
	
	public final static String Biller_Invoice_Delete = "//select[@onchange='SelectAction(this)']";
	public final static String Biller_Invoice_Reason ="//li[text()='End Service']";
	public final static String Biller_Invoice_view ="(//a[@title='View Contract'])[1]";
	public final static String Biller_Invoice_form ="//form[@action='ePayment-ar4.html']";
	
	public final static String Biller_Invoice_Deletebtn = "//button[@id='btnConfirmDelete']";
	public final static String Biller_Invoice_Reasontxt="//input[@type='search']";
	public final static String Biller_Invoice_Deletechkbox="//label[@for='Deleted']";
	public final static String Biller_Invoice_table="//table[@id='tblCustomers']";
	public final static String Biller_Invoice_Templatetype= "//input[@id='BillType_16']";
	public final static String Biller_Invoice_Templatetype_One= "//input[@id='BillType_15']";
	public final static String Admin_TaxEng= "//input[@id='TaxName']";
	public final static String Biller_Individualclient_Email = "//input[@id='Email']";
	public final static String Biller_Individualclient_Refno = "//input[@id='CustomerRefNumber']";
	public final static String Biller_Individualclient_Search = "//button[@id='btnSearch']";
	public final static String Biller_Individualclient_SearchBtn = "//button[@id='btnSearch']";
	public final static String Biller_Individualclient_Edit = "	//td[9]";
	public final static String Biller_Edit = "(//a[@class='mx-1 action bg-accent'])[1]";
	public final static String Biller_Individualclient_Searchname = "//span[contains(text(),'comp2')]";
	public final static String Biller_Corpclient_Searchname = "(//span[contains(text(),'client')])[1]";
	public final static String Biller_Individualclient_SearchByname = "//input[@id='Name']";
	public final static String Biller_Subbiller_Search ="//button[text()='Search']";	
	public final static String Biller_Individualclient_Back ="//a[text()='Back']";
	public final static String Biller_Individualclient_Deactivate ="(//input[@type='checkbox'])[3]";
	public final static String Biller_Individualclient_button="//button[@id='btnConfirmApproveBillerInfo']";
	
	
	public final static String Biller_Confirm_toggle="//button[@id='btnConfirmActivation']";

	
	public final static String Biller_ApprovedMgm_Menu="//a[@id='lnkApprovedBillerList2']";
	public final static String Biller_Individualclient_export="//a[@id='btnExport']";
	public final static String Biller_Individualclient_Corponame = "(//input[@type='text'])[1]";
	public final static String Biller_Individualclient_Customercrnum = "//input[@id='RegistrationNo']";


	//Corporate
	public final static String Biller_Corporateclient_commissioner_Mobile = "//input[@id='CommissionerMobileNo']";
	public final static String Biller_Corporateclient_commissioner_Email = "//input[@id='CommissionerEmail']";
	public final static String Biller_Corporateclient_commissioner_Crno = "//input[@id='CustomerRefNumber']";
	public final static String Biller_Corporateclient_name = "//input[@id='NameAr']";
	public final static String Biller_Corporateclient_Rno = "//input[@id='RegistrationNo']";
	public final static String Biller_Corporateclient_lang = "//label[text()='English']";
	public final static String Biller_Corporateclient_commissioner = "//input[@id='CommissionerNameAr']";
	public final static String Biller_Corporateclient_commissionerID = "//input[@id='CommissionerNationalId']";
	public final static String Biller_Corporateclient_Name = "//input[@id='CompanyName']";
	public final static String Biller_Corporateclient_Save = "//input[@id='btnUpdate']";
	public final static String Biller_Corporateclient_tbl = "//table[@id='tblCompanies']";
	public final static String Biller_Corporateclient_search = "//input[@id='CompanyName']";
	
	//signup

	public final static String Biller_SignUp_Btn ="//a[contains(@href,'BillerCompanySignUp')]";
	public final static String Biller_CompanyName_eField ="//input[@name='CompanyNameAr']";
	public final static String Biller_EconomySector_List ="//select[@name='EconomicSectorID']";
	public final static String Biller_Country_List ="//select[@name='CountryID']";
	public final static String Biller_City_List ="//select[@name='CityID']";
	public final static String Biller_District_eField ="//input[@name='District']";
	public final static String Biller_Street_eField ="//input[@name='Street']";
	public final static String Biller_BuildNo_eField ="//input[@name='BuildingNo']";
	public final static String Biller_PostalCode_eField ="//input[@name='PostalCode']";
	public final static String Biller_MailBox_eField ="//input[@name='MailBox']";
	public final static String Biller_OfficNo_eField ="//input[@name='OfficeNo']";
	public final static String Biller_EmplyName_eField ="//input[@name='EmployeeName']";
	public final static String Biller_EmplyJobTitle_eField ="//input[@name='EmployeeJobTitle']";
	public final static String Biller_EmplyMobileNumber_eField ="//input[@name='EmployeeMobileNo']";
	public final static String Biller_EmplyEmail_eField ="//input[@name='EmployeeEmail']";
	public final static String Biller_CustomerSupPhNo_eField ="//input[@name='CustomerSupportPhoneNo']";
	public final static String Biller_IBANum_eField ="//input[@name='IBAN']";
	public final static String Biller_IBANAttmnt_eField ="//input[@name='IBANAttachment']";
	public final static String Biller_BankCountryType_List ="//select[@name='BankAccountTypeId']";
	public final static String Biller_BankCertAttmnt_eField ="//input[@name='BankCertificateAttachment']";
	public final static String Biller_CRNumber_eField ="//input[@name='RegistrationNo']";
	public final static String Biller_RegiAttachment_eField ="//input[@name='RegistrationAttachment']";
	public final static String Biller_RegistDate_eField ="//input[@name='RegistrationDateHijri']";
	public final static String Biller_RegistDate_Issuedate ="(//tr[td[a[contains(@class,'calendars-today')]]]//following-sibling::td)[1]";
	public final static String Biller_RegistDate_exprDate ="//a[contains(@class,'calendars-today')]";
	public final static String Biller_ExperyDate_eField ="//input[@name='ExpiredRegistrationDateHijri']";
	public final static String Biller_Taxno_eField ="//input[@name='TaxNo']";
	public final static String Biller_IsTaxable_RadBtn ="//div[label[contains(text(),'Taxable')]]/input[@name='IsTaxable']";
	public final static String Biller_NoTaxable_RadBtn ="//div[label[contains(text(),'Non-Taxable')]]/input[@name='Taxable']";
	public final static String Biller_TaxRegisAttmnt_eField ="//input[@name='TaxRegistrationAttachment']";
	public final static String Biller_FirstName_eField ="//input[@name='FirstNameAr']";
	public final static String Biller_SurName_eField ="//input[@name='FatherNameAr']";
	public final static String Biller_GradFatherName_eField ="//input[@name='GrandFatherNameAr']";
	public final static String Biller_LastName_eField ="//input[@name='LastNameAr']";
	public final static String Biller_NationalID_eField ="//input[@name='NationalID']";
	public final static String Biller_CommisionIdentyAttmnt_eField ="//input[@name='CommissionerIdentityAttachment']";
	public final static String Biller_MemDumAssoAttmnt_eField ="//input[@name='MemorandumOfAssociationAttachment']";
	public final static String Biller_AuthLterTemltAttmnt_eField ="//span[@id='lblAuthorizationLetterTemplateAttachment']";
	public final static String Biller_CommisionPhNo_eField ="//input[@name='CommissionerPhoneNo']";
	public final static String Biller_CommisionEmail_eField ="//input[@name='CommissionerEmail']";
	public final static String Biller_UserID_eField ="//input[@name='Username']";
	public final static String Biller_Password_eField ="//input[@name='Password']";
	public final static String Biller_ConfPawd_eField ="//input[@name='ConfirmPassword']";
	public final static String Biller_Confirmation_CheckBox="//input[@name='Confirmation']";
	public final static String Biller_ReCatchBox_eField ="//iframe[@title='reCAPTCHA']";
	public final static String Biller_CatchBox_eField ="//span[@id='recaptcha-anchor']";
	public final static String Biller_SignUp_btn="//input[@id='btnSignUp']";
	public final static String Biller_RegisterComp_btn ="//h4[contains(text(),'Registration completed successfully')]";
	public final static String Biller_Close_btn ="//button[text()='Close']";
	public final static String Biller_AuthTempl_Link ="//a[text()='Authorization Letter Sample']";
	public final static String Biller_AttachetedImage_Link="//input[contains(@accept,'image') and (@name='IBANAttachment')]";
	public final static String Biller_Receivable_Link="//a[contains(text(),'Receivables')]";
	public final static String Biller_ExportBill_Link="(//a[contains(text(),'Exported Bills')])[2]";
	public final static String Biller_AddInvoice_btn="//button[@id='btnAddInvoice']";
	public final static String Biller_AddInvoice_Header="//h6[text()='Create Invoice']";
	public final static String Biller_Invoice_IndividualRdv="//input[@id='rdIndividual']";
	public final static String Biller_Invoice_CopoRdv="//input[@id='rdCompany']";
//	public final static String Biller_Invoice_IndividualRdv="//label[@for='rdIndividual']";
//	public final static String Biller_Invoice_CopoRdv="//label[@for='rdCompany']";
	public final static String Biller_Invoice_CustIDListindi="//select[@name='CustomerId']/following-sibling::span//span[@class='select2-selection__arrow']";
	public final static String Biller_Invoice_CustIDListcorpo="//select[@name='CompanyId']/following-sibling::span//span[@class='select2-selection__arrow']";
	public final static String Biller_Invoice_SBilIdList="//select[@name='SubBillerId']/following-sibling::span//span[contains(@class,'arrow')]";
	public final static String Biller_Invoice_SBilShareamountFil="//input[@id='SubBillerShareAmount']";
	public final static String Biller_Invoice_SBilSharePerFil="//input[@id='SubBillerSharePercentage']";
	public final static String Biller_Invoice_TemplateList="//select[@id='InvoiceTemplateId']";
	public final static String Biller_Invoice_Create="//button[@id='btnCreateInvoice']";
	public final static String Biller_Invoice_AddProductBtn="//a[@id='btnAddProductModal']";
	public final static String Biller_Invoice_Subbill="//input[@id='rdSubbillerIndividual']";
	public final static String Biller_Invoice_TaxPric="//input[@id='tbxPrice']";
	public final static String Biller_Invoice_ProductID="//select[@name='ProductId']";
	public final static String Biller_Invoice_AddBtn="//button[.='Add']";
	public final static String Biller_Invoice_DateInvoc="//input[@name='IssueDate']";
	public final static String Biller_Invoice_DurationID="//select[@id='DurationTypeId']";
	public final static String Biller_Invoice_MinTax="//input[@name='MinLimit']";
	public final static String Biller_Invoice_CreateReapeat="//button[@id='btnCreateRepeatInvoice']";
	public final static String Biller_Invoice_Conditon="//textarea[@id='txtConditions']";
	public final static String Biller_Invoice_Conditonbtn="//div[@id='divTerms']//input";
	public final static String Biller_Invoice_Descript="//textarea[@id='txtBillDescription']";
	public final static String Biller_Invoice_Descript1="//textarea[@id='txtDescription_1']";
//	public final static String Biller_Invoice_SaveButton="//button[@id='btnUpdateBill']";
	public final static String Biller_Invoice_SaveButton="//button[@id='btnCreateInvoice']";
	public final static String Biller_Invoice_ExportButton="//button[@id='btnUpdateBill']";
	public final static String Biller_Invoice_Exportandcreatebtn="//button[@id='btnExportInvoice']";
	public final static String Biller_Invoice_Billnumber="//input[@id='billNo']";
	public final static String Biller_Invoice_Searchbtn="//button[@id='btnSearch']";
	public final static String Biller_Invoice_Count="(//table[@id='tblBillList']//tbody/tr[@role='row'])";
	public final static String Biller_Invoice_AfteraddCount="(//table[@id='tblInvoiceList']//tbody/tr[@role='row'])";
	public final static String Biller_Invoice_AfteraddInvoice="(//table[@id='tblBillList']//tbody/tr[@role='row'])";
	public final static String Biller_ExportExcel="//a[@id='btnExport']";
	public final static String Biller_InvoiceLastCheckBox="(//table[@id='tblBillList']//tbody/tr[@role='row'])//input[@type='checkbox'][last()]";
	public final static String Biller_Export_CancellationBtn="//button[@id='btnCancelSelected']";
	public final static String Biller_Export_PayOutsideBtn="//button[@id='btnPayCashSelected']";
	public final static String Biller_Export_ViewContactBtn="(//table[@id='tblBillList']//tbody/tr[@role='row'])//a[@title='View Contract'][last()]";
	public final static String Biller_Invoice_ClientRoleId="(//li[@role='treeitem'])";
	public final static String Biller_Invoice_NextBtn="//a[text()='Next']";
	public final static String Biller_Invoice_Next="//li[a[text()='Next']][contains(@class,'next disabled')]";
	public final static String Biller_Invoice_GetBilId="(//td[contains(text(),' Bill Number')]/span)[1]";
	public final static String Biller_Invoice_BillNo="//a[contains(@href,'billNo')]";
	public final static String Biller_Invoice_BillerNumber="//label[contains(text(),'Bill Number')]/h6";
	public final static String Biller_Invoice_PrintButton="//button[@id='btnPrintInvoice']";
	public final static String Biller_ExportContact_Link="//a[contains(text(),'Exported Contracts')]";
	public final static String Biller_ExportContact_InvID="//a[contains(@href,'invoiceId')]";
	public final static String Biller_Invoice_GetContactId="(//td[contains(text(),' Bill Number')]/span)[1]";
	public final static String Biller_ExportContact_ContactHeader="//label[contains(text(),'Contract Number')]/following-sibling::span";
	public final static String Biller_ExportContact_InvoiceDetails="//h6[text()='Invoice Details']";
	public final static String Biller_Tamplate_Table="(//table[contains(@id,'DataTables_Table')]//tbody/tr[@role='row'])";
	public final static String Biller_Tamplate_UpdateBtn="//button[contains(@id,'btnUpdate')]";
	public final static String Biller_Tamplate_UpdateTitleHdr="//h5[@id='exampleModalLongTitle']";
	public final static String Biller_Tamplate_UpdateDesHdr="//label[text()='Description']";
	public final static String Biller_Tamplate_UpdateInVTyeHdr="//label[text()='Invoice Type']";
	public final static String Biller_Tamplate_AddTitleHdr="//h5[@id='exampleModalLongTitle']";
	public final static String Biller_Tamplate_AddTemplNameArbicHdr="//label[text()='Template Name in Arabic']";
	public final static String Biller_Tamplate_AddTemplNameEngHdr="//label[text()='Template Name in English']";
	public final static String Biller_Tamplate_AddRefercodeHdr="(//label[text()='Reference Code'])[2]";
	public final static String Biller_Tamplate_AddActDdeacHdr="(//label[text()='Activate/Deactivate'])[1]";
	public final static String Biller_Tamplate_AddBillPaymentyHdr="(//label[text()='Bill Payment'])[2]";
	public final static String Biller_Tamplate_DeleteBtn="//button[contains(@id,'btnDelete')]";
	public final static String Biller_Tamplate_DeletePop="//h5[@id='ConfirmActivationMessage']";
	public final static String Biller_Tamplate_DeleteConfBtn="// button[@id='btnConfirm']";
	public final static String Biller_Tamplate_DeleteNoBtn="// button[text()='No']";
	public final static String Biller_Product_Table="(//table[@id='tblProducts']//tbody/tr[@role='row'])";
	public final static String Biller_Product_PName="(//table[@id='tblProducts']//tbody/tr[@role='row'])[1]/td[3]";
	public final static String Biller_Product_PCate="(//table[@id='tblProducts']//tbody/tr[@role='row'])[1]/td[4]";
	public final static String Biller_Product_NameInput="//input[@id='Name']";
	public final static String Biller_Product_SearchIDlist="//select[@id='ServiceId']";
	public final static String Biller_Product_SeachBtn="//button[@id='btnSearch']";
	public final static String Biller_Product_NoData="//td[contains(text(),'No data available in table')]";
	public final static String Biller_Product_ToggleBtn="(//table[@id='tblProducts']//tbody/tr[@role='row'])[1]//input[@class='switch']";
	public final static String Biller_Product_ActivePop="//h5[@id='ConfirmActivationMessage']";
	public final static String Biller_Product_ActiveConfbtn="//button[@id='btnConfirmActivation']";
	public final static String Biller_Menu_Discount ="//a[text()='Discounts Management']";
	public final static String Biller_Discount_AddBtn ="//button[@id='btnAddDiscount']";
	public final static String Biller_Discount_EngInp ="//input[@id='NameEn']";
	public final static String Biller_Discount_AtrabInp ="//input[@id='NameAr']";
	public final static String Biller_Discount_Percent ="//input[@id='Value']";
	public final static String Biller_Discount_toggle ="//label[@for='status']";
	public final static String Biller_Discount_Verify ="//table[@id='tblDiscounts']//td[1]";
	public final static String Biller_Discount_Deactivatetgl="//span[@class='switch switch-sm']";
	public final static String Biller_Discount_Deact_confirm="//h5[text()='Cancel activation?']";
	public final static String Biller_Discount_Canyes="//button[@id='btnConfirmActivation']";
	
	public final static String Biller_Discount_AddDiscBtn ="//button[contains(text(),'Add Discount')]";
	public final static String Biller_Discount_DiscName ="//input[@id='DiscountName']";
	public final static String Biller_Discount_SearchBtn ="//button[contains(text(),'Search')]";
	public final static String Biller_Discount_DeleteBtn ="//a[@class='mx-1 action bg-danger deleteItem']";	
	public final static String Biller_Tamplate_ConfirmDeletePop="//h5[@id='ConfirmDeleteMessage']";
	public final static String Biller_Discount_YesConfBtn ="//button[@id='btnConfirmDelete']";
	public final static String Biller_Systemmgmt_TempBenificaryName = "//input[@name='TempBenificaryName']";
	public final static String Biller_Systemmgmt_BillerCode = "//input[@name='BillerCode']";
	public final static String Biller_Systemmgmt_TransferDuration = "//input[@name='TransferDuration']";
	public final static String Biller_Systemmgmt_BillerAliasNameAr = "//input[@name='BillerAliasNameAr']";
	public final static String Biller_Systemmgmt_BillerAliasNameEn = "//input[@name='BillerAliasNameEn']";
	public final static String Biller_Systemmgmt_BillingCatgeoryType = "//select[@id='BillerCategoryId']";
	public final static String Biller_Systemmgmt_HasSubBillers = "(//input[@name='HasSubBillers'])[1]";
	public final static String Biller_Systemmgmt_HasIndividualSubBillers = "(//input[@name='HasIndividualSubBillers'])[1]";
	public final static String Biller_Systemmgmt_HasEnterpriseSubBillers= "(//input[@name='HasEnterpriseSubBillers'])[1]";
	public final static String Biller_Systemmgmt_IsUrgentBillUploader= "(//input[@name='IsUrgentBillUploader'])[1]";
	public final static String Biller_Systemmgmt_HasMaximumInvoiceNumberPerDay= "(//input[@name='HasMaximumInvoiceNumberPerDay'])[1]";
	public final static String Biller_Systemmgmt_MaximumInvoiceNumber= "//input[@name='MaximumInvoiceNumber']";
	public final static String Biller_Systemmgmt_HasMaximumInvoiceAmountPerDay= "(//input[@name='HasMaximumInvoiceAmountPerDay'])[1]";
	public final static String Biller_Systemmgmt_Btnapprove= "//button[@id='btnApprove']";
	public final static String Biller_Systemmgmt_MaximumInvoiceAmount= "(//input[@name='MaximumInvoiceAmount'])[1]";
	public final static String Biller_Systemmgmt_Super= "(//input[@name='IsSuperBiller'])[1]";
	public final static String Biller_Systemmgmt_Tracker= "(//input[@name='IsTrackedBiller'])[1]";
	public final static String Biller_Systemmgmt_Confirm= "//button[@id='btnConfirmSetAsSuperBiller']";
	public final static String Biller_Systemmgmt_NewSuperBiller= "//select[@name='NewSuperBillerId']";
	public final static String Biller_Menu_UserManagement ="//a[text()='Groups Management']";
	public final static String Biller_Menu_UserList ="//a[text()='Users List']";
	public final static String Biller_UserList_AddUserBt ="//button[@id='btnAddUser']";
	public final static String Biller_UserListAdd_NameInput ="//input[@id='NameAR']";
	public final static String Biller_UserListAdd_EmailInput ="//input[@id='EMail']";
	public final static String Biller_UserListAdd_PhoneInput ="//input[@id='Phone']";
	public final static String Biller_UserListAdd_GroupCheckBox ="//div[@id='GroupsListDiv']//input";
	public final static String Biller_UserListAdd_GroupCheckBox2 ="//input[@id=75]";
	public final static String Biller_UserListAdd_AddUserBtPop ="//button[@id='btnAddUser']";
	public final static String Biller_UserListSearch_NameBt ="//input[@id='Name']";
	public final static String Biller_UserListSearch_EmailBt ="//input[@id='Email']";
	public final static String Biller_UserListSearch_SaerchBt ="//button[@id='btnSearch']";
	public final static String Biller_UserList_DeleteBtn ="//a[contains(@id,'btndelete')]";	
	public final static String Biller_UserList_ConfirmDeletePop="//h5[@id='ConfirmDeleteMessage']";
	public final static String Biller_UserList_YesConfBtn ="//button[@id='btnConfirmDelete']";
	public final static String Biller_Individualclient_Invoice="//input[@id='rdIndividual']";
//	public final static String Biller_Individualclient_Invoice_cName="//span[@id='select2-CustomerId-container']";
	public final static String Biller_Individualclient_Invoice_ChooseName="//select[@id='CustomerId']";
	public final static String Biller_Invoice_Fixed="//input[@name='SubBillerShareAmount']";
	public final static String Biller_Invoice_Percentage="//input[@name='SubBillerSharePercentage']";
	
	
	public final static String Admin_Receivable_Link="//a[contains(text(),'Receivables')]";
	public final static String Admin_Billerno_search="//input[@id='billNo']";
	public final static String Admin_Billerno_button="//button[@id='btnSearch']";
	public final static String Admin_ExportBill_Link="//a[contains(text(),'Exported Bills')]";
	public final static String Admin_AddInvoice_btn="//button[@id='btnAddInvoice']";
	public final static String Admin_AddInvoice_Header="//h6[text()='Create Invoice']";
	public final static String Admin_Invoice_IndividualRdv="//input[@id='rdIndividual']";
	public final static String Admin_Invoice_CopoRdv="//input[@id='rdCompany']";
	public final static String Admin_Invoice_ComCustIDList="//select[@name='CompanyId']/following-sibling::span//span[@class='select2-selection__arrow']";
	public final static String Admin_Invoice_CustIDList="//select[@name='CustomerId']/following-sibling::span//span[@class='select2-selection__arrow']";
	public final static String Admin_Invoice_SBilIdList="//select[@name='SubBillerId']/following-sibling::span//span[@class='select2-selection__arrow']";
	public final static String Admin_Invoice_SBilShareamountFil="//input[@id='SubAdminShareAmount']";
	public final static String Admin_Invoice_SBilSharePerFil="//input[@id='SubAdminSharePercentage']";
	public final static String Admin_Invoice_TemplateList="//select[@id='InvoiceTemplateId']";
	public final static String Admin_Invoice_Create="//button[@id='btnCreateInvoice']";
	public final static String Admin_Invoice_AddProductBtn="//a[@id='btnAddProductModal']";
	public final static String Admin_Invoice_Subbill="//input[@id='rdSubAdminIndividual']";
	public final static String Admin_Invoice_TaxPric="//input[@id='tbxPrice']";
	public final static String Admin_Invoice_ProductID="//select[@name='ProductId']";
	public final static String Admin_Invoice_AddBtn="//div[@class='modal-footer']/button[@id='btnAddProduct']";
	public final static String Admin_Invoice_DateInvoc="//input[@name='IssueDate']";
	public final static String Admin_Invoice_DurationID="//select[@name='DurationTypeId']";
	public final static String Admin_Invoice_MinTax="//input[@name='MinLimit']";
	public final static String Admin_Invoice_CreateReapeat="//button[@id='btnCreateRepeatInvoice']";
	public final static String Admin_Invoice_Conditon="//textarea[@id='txtConditions']";
	public final static String Admin_Invoice_Conditonbtn="(//div[@id='divTerms']//input)[1]";
	public final static String Admin_Invoice_Descript="//textarea[@id='txtBillDescription']";
	public final static String Admin_Invoice_Descript1="//textarea[@id='txtDescription_1']";
	public final static String Admin_Invoice_SaveButton="//button[@id='btnUpdateBill']";
	public final static String Admin_Invoice_ExportButton="//button[@id='btnUpdateBill']";
	public final static String Admin_Invoice_Count="(//table[@id='tblBillList']//tbody/tr[@role='row'])";
	public final static String Admin_Invoice_AfteraddCount="(//table[@id='tblInvoiceList']//tbody/tr[@role='row'])";
	public final static String Admin_Invoice_AfteraddInvoice="(//table[@id='tblBillList']//tbody/tr[@role='row'])";
	public final static String Admin_Invoice_ClientRoleId="(//li[@role='treeitem'])";
	public final static String Admin_RegistDate_exprDate ="//a[contains(@class,'calendars-today')]";
	public final static String Admin_InvoiceLastCheckBox="(//table[@id='tblBillList']//tbody/tr[@role='row'])//input[@type='checkbox'][last()]";
	public final static String Admin_Invoice_GetBilId="(//td[contains(text(),' Bill Number')]/span)[1]";
	public final static String Admin_ExportContact_Link="//a[contains(text(),'Exported Contracts')]";
	public final static String Admin_Invoice_GetContactId="(//td[contains(text(),' Bill Number')]/span)[1]";
	public final static String Admin_Invoice_NextBtn="//a[text()='Next']";
	public final static String Admin_Invoice_Next="//li[a[text()='Next']][contains(@class,'next disabled')]";
	public final static String Admin_Invoice_NextPrevLink="(//li[a[text()='Next']]/preceding-sibling::li)[last()]/a";
	public final static String Admin_Export_CancellationBtn="//button[@id='btnCancelSelected']";
	public final static String Admin_Export_PayOutsideBtn="//button[@id='btnPayCashSelected']";
	public final static String Admin_Export_ViewContactBtn="(//table[@id='tblBillList']//tbody/tr[@role='row'])//a[@title='View Contract'][last()]";
	public final static String Admin_ExportExcel="//a[@id='btnExport']";
	public final static String Admin_ExportExcel_Verify="//span[@id='spnUnderProcessing']";
	public final static String Admin_Invoice_BillNo="//a[contains(@href,'billNo')]";
	public final static String Admin_Invoice_BillerNumber="//label[contains(text(),'Bill Number')]/h6";
	public final static String Admin_Invoice_PrintButton="//button[@id='btnPrintInvoice']";
	public final static String Admin_ExportContact_InvID="//a[contains(@href,'invoiceId')]";
	public final static String Admin_ExportContact_ContactHeader="//label[contains(text(),'Contract Number')]/following-sibling::span";
	public final static String Admin_ExportContact_InvoiceDetails="//h6[text()='Invoice Details']";
	
	public final static String Admin_Client = "//a[@id='lnkMyClients2']";
	public final static String Admin_Add_Individualclient = "//a[@id='lnkCustomerList2']";
	public final static String Admin_Add_Individualclient_Button = "//button[@id='btnAddCustomer']";
	public final static String Admin_Corporate_Name = "//input[@id='CompanyName']";
	public final static String Admin_ClientName = "//input[@id='Name']";
	public final static String Admin_CR_Number= "//input[@id='RegistrationNo']";
	public final static String Admin_IN_nationalID= "//input[@id='IdNumber']";
	public final static String Admin_ClientRef_Number= "//input[@id='CustomerRefNumber']";
	public final static String Admin_IN_ClientRef_Number= "//input[@id='CustomerRefNumber']";
	public final static String Admin_ClientSearch_button= "//button[@id='btnSearch']";
	public final static String Admin_Individualclient_fname = "//input[@id='FirstName']";
	public final static String Admin_Individualclient_sname = "//input[@id='SecondName']";
	public final static String Admin_Individualclient_tname = "//input[@id='ThirdName']";
	public final static String Admin_Individualclient_lname = "//input[@id='LastName']";
	public final static String Admin_Individualclient_IdNumber = "//input[@id='IdNumber']";
	public final static String Admin_Individualclient_DateOfBirth = "//input[@id='DateOfBirth']";
	public final static String Admin_Individualclient_DateOfYear = "//select[@title='Change the year']";
	public final static String Admin_Individualclient_DateOfMonth = "//select[@title='Change the month']";
	public final static String Admin_Individualclient_Email = "//input[@id='Email']";
	public final static String Admin_Individualclient_Refno = "//input[@id='CustomerRefNumber']";
	public final static String Admin_Individualclient_MobileNo = "//input[@id='MobileNo']";
	public final static String Admin_Individualclient_Add = "//input[@id='btnAdd']";
	
	public final static String Admin_Settings = "//a[@id='lnkMySettings']";
	public final static String Admin_Individualclient_Name = "//input[@id='Name']";
	public final static String Admin_Invoice_Search ="//button[text()='Search']";
	public final static String Admin_Add_Invoice_template = "//a[@id='lnkInvoiceSetting2']";
	public final static String Admin_Add_Invoice_Button = "//button[@id='btnAddTemplate']";
	public final static String Admin_Invoice_TemplateArabic = "//input[@id='NameAr']";
	public final static String Admin_Invoice_TemplateEng= "//input[@id='NameEn']";
	public final static String Admin_Invoice_Templatetype= "//input[@id='BillType_16']";
	public final static String Admin_Invoice_Templatetype_One= "//input[@id='BillType_15']";
	public final static String Admin_Invoice_Add = "//button[@id='btnAdd']";
	public final static String Admin_Tamplate_AddTitleHdr="//h5[@id='exampleModalLongTitle']";
	public final static String Admin_Tamplate_AddTemplNameArbicHdr="//label[text()='Template Name in Arabic']";
	public final static String Admin_Tamplate_AddTemplNameEngHdr="//label[text()='Template Name in English']";
	public final static String Admin_Tamplate_AddRefercodeHdr="//label[text()='Reference Code']";
	public final static String Admin_Tamplate_AddActDdeacHdr="(//label[text()='Activate/Deactivate'])[1]";
	public final static String Admin_Tamplate_AddBillPaymentyHdr="//label[text()='Bill Payment']";
	
	
	public final static String Admin_Tamplate_Table="(//table[contains(@id,'DataTables_Table')]//tbody/tr[@role='row'])";
	public final static String Admin_Tamplate_UpdateBtn="//button[contains(@id,'btnUpdate')]";
	public final static String Admin_Tamplate_UpdateTitleHdr="//h5[@id='exampleModalLongTitle']";
	public final static String Admin_Tamplate_UpdateDesHdr="//label[text()='Description']";
	public final static String Admin_Tamplate_UpdateInVTyeHdr="//label[text()='Invoice Type']";
	public final static String Admin_Tamplate_DeleteBtn="//button[contains(@id,'btnDelete')]";
	public final static String Admin_Tamplate_DeletePop="//h5[@id='ConfirmActivationMessage']";
	public final static String Admin_Tamplate_DeleteConfBtn="// button[@id='btnConfirm']";
	public final static String Admin_Tamplate_DeleteNoBtn="// button[text()='No']";
	
	public final static String Admin_Prod_NameArabic = "(//input[@id='Name'])[2]";
	public final static String Admin_Prod_Ref = "//input[@id='Code']";
	public final static String Admin_Prod_Description = "//textarea[@id='Description']";
	public final static String Admin_Invoice_TemplateEnglish= "//input[@id='NameEn']";
	public final static String Admin_Prod_Price= "//input[@id='Price']";
	public final static String Admin_Prod_MaxPrice= "//input[@id='MaxPrice']";
	
	public final static String Admin_Prod_MinPrice= "//input[@id='MinPrice']";
	public final static String Admin_Prod_Addbutton="//button[@id='btnAddProduct']";
	public final static String Admin_Individualclient_fistname = "//input[@id='FirstName']";
	public final static String Admin_Maxlimit = "//input[@id='Limit']";
	public final static String Admin_TransferDuration = "//input[@id='TransferDuration']";
	public final static String Admin_AzimFee = "//input[@id='AzimFee']";
	public final static String Admin_sadadFee = "//input[@id='sadadFee']";
	public final static String Admin_AdminAliasNameEn = "//input[@id='AdminAliasNameEn']";
	public final static String Admin_MaximumInvoiceAmount = "//input[@id='MaximumInvoiceAmount']";
	public final static String Admin_Imgdownload = "//a[@class='text-white']";
	public final static String Admin_InvoiceName= "(//a[@target='_blank'])[9]";
	public final static String Admin_Invoice_Select="(//select[@id='ServiceId'])[2]";
	
	//public final static String Admin_Individualclient_Search = "//button[@id='btnSearch']";
	public final static String Admin_Individualclient_Search = "//button[@id='btnSearch']";
	public final static String Admin_Invoice_Delete = "//select[@onchange='SelectAction(this)']";
	public final static String Admin_InvoiceDelete = "(//select[@onchange='SelectAction(this)'])[1]";
	public final static String Admin_Invoice_Reasontxt="//input[@type='search']";
	public final static String Admin_Invoice_Deletebtn = "//button[@id='btnConfirmDelete']";
	public final static String Admin_Invoice_Deletechkbox="//label[@for='Deleted']";
	public final static String Admin_Invoice_table="//table[@id='tblCustomers']";
	public final static String Admin_Individualclient_SearchByname = "//input[@id='Name']";
	public final static String Admin_Corpclient_Searchname = "(//span[contains(text(),'client')])[1]";
	public final static String Admin_Corpclient_SearchName = "(//span[contains(text(),'FullNameOne')])[1]";
	public final static String Admin_Individualclient_Back ="//a[text()='Back']";
	public final static String Admin_Invoice_Fixed="//input[@name='SubBillerShareAmount']";
	public final static String Admin_Invoice_Percentage="//input[@name='SubBillerSharePercentage']";
	
	public final static String Admin_Add_Companyclient = "//a[@id='lnkCompanyList2']";
	public final static String Admin_Corporateclient_name = "//input[@id='NameAr']";
	public final static String Admin_CorporateclientName= "//input[@id='CompanyName']";
	public final static String Admin_Corporateclient_Rno = "//input[@id='RegistrationNo']";
	public final static String Admin_Corporateclient_lang = "//label[text()='English']";
	public final static String Admin_Corporateclient_commissioner = "//input[@id='CommissionerNameAr']";
	public final static String Admin_Corporateclient_commissionerID = "//input[@id='CommissionerNationalId']";
	public final static String Admin_Corporateclient_commissioner_Mobile = "//input[@id='CommissionerMobileNo']";
	public final static String Admin_Corporateclient_commissioner_Email = "//input[@id='CommissionerEmail']";
	public final static String Admin_Corporateclient_commissioner_Crno = "//input[@id='CustomerRefNumber']";

	public final static String Admin_Individualclient_CustomerRefNumber = "//input[@id='CustomerRefNumber']";
	public final static String Admin_Individualclient_Companyname = "//input[@id='CompanyName']";
	public final static String Admin_Corporateclient_tbl = "//table[@id='tblCompanies']";
	public final static String Admin_Corporateclient_search = "//input[@id='CompanyName']";
	public final static String Admin_Individualclient_Searchname = "//span[contains(text(),'comp')]";
	public final static String Admin_Corporateclient_Save = "//input[@id='btnUpdate']";
	public final static String Admin_Individualclient_Deactivate ="(//input[@type='checkbox'])[3]";
	public final static String Admin_Individualclient_button="//button[text()='Yes']";
	public final static String Admin_Company_ToggleBtn="(//table[@id='tblCompanies']//tbody/tr[@role='row'])[1]//input[@class='switch']";
	public final static String Admin_Company_ToggleButton="(//table[@id='tblCustomers']//tbody/tr[@role='row'])[1]//input[@class='switch']";
	public final static String Admin_Compan_ActivePop="//h5[@id='ConfirmActivationMessage']";
	public final static String Admin_Compan_ActiveConfbtn="// button[@id='btnConfirmActivation']";
	public final static String Admin_Individualclient_export="//a[@id='btnExport']";
	public final static String Admin_Invoice_form ="//form[@action='ePayment-ar4.html']";
	public final static String Admin_Invoice_view ="(//a[@title='View Contract'])[1]";

	public final static String Admin_Product_ActivePop="//h5[@id='ConfirmActivationMessage']";
	public final static String Admin_Product_ActiveConfbtn="// button[@id='btnConfirmActivation']";
	public final static String Admin_Product_ToggleBtn="(//table[@id='tblProducts']//tbody/tr[@role='row'])[1]//input[@class='switch']";
	public final static String Admin_Systemmgmt_AddProductBtn="//button[@id='btnAddProduct']";
	public final static String Admin_AddBtn="//div[@class='modal-footer']/button[@id='btnAddProduct']";
	public final static String Admin_Add_Product = "//a[text()='Products Management']";
	public final static String Admin_Add_Cat = "//button[text()='Add']";
	public final static String Admin_Add_tax = "(//button[text()='Add Tax'])[2]";
	public final static String Admin_Add_RefError = "//span[contains(text(),' already')]";

	public final static String Admin_Status = "//input[@id='status']";
	public final static String Admin_Cat_Addbtn = "//button[@id='btnAddService']";
	public final static String Admin_Prod_CatArabic = "(//input[@id='Name'])[2]";
	public final static String Admin_taxArabic = "//input[@id='NameAr']";
	public final static String Admin_PercentageValue = "//input[@id='Value']";
	public final static String Admin_Prod_CatEng= "//input[@id='NameEn']";
	public final static String Admin_SearchCat ="//button[text()='Search']";	
	public final static String Admin_Updatebtn ="//button[@onclick='Update(this);']";
	public final static String Admin_UpdateSearch ="//input[@id='Name']";
	public final static String Admin_Prod_CatEnglish ="(//input[@id='Name'])[1]";
	public final static String Admin_CatTable ="//table[@id='DataTables_Table_0']";
	public final static String Admin_UpdateCat = "//button[text()='Save Changes']";
	public final static String Admin_Tax_Addbtn = "//button[@id='btnAddTax']";
	public final static String Admin_Prod_Category="//a[@id='lnkServiceList2']";
	public final static String Admin_Tax_Mgmt="//a[@id='lnkTaxList2']";
	public final static String Admin_Tax_ToggleBtn="(//table[@id='tblTaxes']//tbody/tr[@role='row'])[1]//input[@class='switch']";

	public final static String Admin_Prod_Pricelist= "//li[@class='select2-search select2-search--inline']";
	public final static String Admin_Pricelist= "//li[contains(text(),'price')]";
	public final static String Admin_Search ="//button[text()='Search']";	
	public final static String Admin_Sytemmanagement = "//a[@id='lnkSystemMangement2']";
	public final static String Admin_Update = "//button[@id='btnUpdate']";
	public final static String Admin_Product_EditLink="//table[contains(@id,'tblProducts')]//tbody/tr[@role='row']/td/a";

	
	
	public final static String Admin_SignUp_Btn ="//a[contains(@href,'BillerCompanySignUp')]";
	public final static String Admin_CompanyName_eField ="//input[@name='CompanyNameAr']";
	public final static String Admin_EconomySector_List ="//select[@name='EconomicSectorID']";
	public final static String Admin_Country_List ="//select[@name='CountryID']";
	public final static String Admin_City_List ="//select[@name='CityID']";
	public final static String Admin_District_eField ="//input[@name='District']";
	public final static String Admin_Street_eField ="//input[@name='Street']";
	public final static String Admin_BuildNo_eField ="//input[@name='BuildingNo']";
	public final static String Admin_PostalCode_eField ="//input[@name='PostalCode']";
	public final static String Admin_MailBox_eField ="//input[@name='MailBox']";
	public final static String Admin_OfficNo_eField ="//input[@name='OfficeNo']";
	public final static String Admin_EmplyName_eField ="//input[@name='EmployeeName']";
	public final static String Admin_EmplyJobTitle_eField ="//input[@name='EmployeeJobTitle']";
	public final static String Admin_EmplyMobileNumber_eField ="//input[@name='EmployeeMobileNo']";
	public final static String Admin_EmplyEmail_eField ="//input[@name='EmployeeEmail']";
	public final static String Admin_CustomerSupPhNo_eField ="//input[@name='CustomerSupportPhoneNo']";
	public final static String Admin_IBANum_eField ="//input[@name='IBAN']";
	public final static String Admin_IBANAttmnt_eField ="//input[@name='IBANAttachment']";
	public final static String Admin_BankCountryType_List ="//select[@name='BankAccountTypeId']";
	public final static String Admin_BankCertAttmnt_eField ="//input[@name='BankCertificateAttachment']";
	public final static String Admin_CRNumber_eField ="//input[@name='RegistrationNo']";
	public final static String Admin_RegiAttachment_eField ="//input[@name='RegistrationAttachment']";
	public final static String Admin_RegistDate_eField ="//input[@name='RegistrationDateHijri']";
	public final static String Admin_RegistDate_Issuedate ="(//tr[td[a[contains(@class,'calendars-today')]]]//following-sibling::td)[1]";
	public final static String Admin_ExperyDate_eField ="//input[@name='ExpiredRegistrationDateHijri']";
	public final static String Admin_Taxno_eField ="//input[@name='TaxNo']";
	public final static String Admin_IsTaxable_RadBtn ="//div[label[contains(text(),'Taxable')]]/input[@name='IsTaxable']";
	public final static String Admin_NoTaxable_RadBtn ="//div[label[contains(text(),'Non-Taxable')]]/input[@name='Taxable']";
	public final static String Admin_TaxRegisAttmnt_eField ="//input[@name='TaxRegistrationAttachment']";
	public final static String Admin_FirstName_eField ="//input[@name='FirstNameAr']";
	public final static String Admin_SurName_eField ="//input[@name='FatherNameAr']";
	public final static String Admin_GradFatherName_eField ="//input[@name='GrandFatherNameAr']";
	public final static String Admin_LastName_eField ="//input[@name='LastNameAr']";
	public final static String Admin_NationalID_eField ="//input[@name='NationalID']";
	public final static String Admin_CommisionIdentyAttmnt_eField ="//input[@name='CommissionerIdentityAttachment']";
	public final static String Admin_MemDumAssoAttmnt_eField ="//input[@name='MemorandumOfAssociationAttachment']";
	public final static String Admin_AuthLterTemltAttmnt_eField ="//span[@id='lblAuthorizationLetterTemplateAttachment']";
	public final static String Admin_CommisionPhNo_eField ="//input[@name='CommissionerPhoneNo']";
	public final static String Admin_CommisionEmail_eField ="//input[@name='CommissionerEmail']";
	public final static String Admin_UserID_eField ="//input[@name='Username']";
	public final static String Admin_Password_eField ="//input[@name='Password']";
	public final static String Admin_ConfPawd_eField ="//input[@name='ConfirmPassword']";
	public final static String Admin_Confirmation_CheckBox="//input[@name='Confirmation']";
	public final static String Admin_ReCatchBox_eField ="//iframe[@title='reCAPTCHA']";
	public final static String Admin_CatchBox_eField ="//span[@id='recaptcha-anchor']";
	public final static String Admin_SignUp_btn="//input[@id='btnSignUp']";
	public final static String Admin_Close_btn ="//button[text()='Close']";
	public final static String Admin_AttachetedImage_Link="//input[contains(@accept,'image') and (@name='IBANAttachment')]";
	public final static String Admin_RegisterComp_btn ="//h4[contains(text(),'Registration completed successfully')]";
	public final static String Admin_Link = "//a[text()='Biller Login']";
	public final static String Admin_NoAppBillerMangm="//a[text()='Not Approved Billers Management']";
	public final static String Admin_SystemMgm_SearchItem="//input[@name='Name']";
	public final static String Admin_SystemMgm_Searchbtn="//button[@id='btnSearch']";
	public final static String Admin_SystemMgm_BillerAliasName="//input[@name='BillerAliasNameAr']";
	public final static String Admin_SystemMgm_BillerActivateBtn="(//a[contains(@href,'BillerActivation')])[1]";
	public final static String Admin_SystemMgm_BillerAliasEnName="//input[@name='BillerAliasNameEn']";
	public final static String Admin_SystemMgm_IsBiller="(//input[@name='IsSuperBiller'])[2]/preceding-sibling::input";
	public final static String Admin_SystemMgm_IsBillerYesBtn="(//button[@id='btnConfirmSetAsSuperBiller'])";
	public final static String Admin_SystemMgm_SavesBtn="(//input[@id='btnSave'])";
	public final static String Admin_SystemMgm_SaveYesBtn="(//button[@id='btnConfirmSaveBillerInfo'])";
	public final static String Admin_SystemMgm_BillerCode="//input[@name='BillerCode']";
	public final static String Admin_SystemMgm_BillerTemBenificary="//input[@name='TempBenificaryName']";
	public final static String Admin_SystemMgm_BillerTransferDura="//input[@name='TransferDuration']";
	public final static String Admin_SystemMgm_BillerCategoryID="//select[@name='BillerCategoryId']";
	public final static String Admin_SystemMgm_ApprovalBtn="//button[contains(text(),'Approval')]";
	public final static String Admin_SystemMgm_ApprovalYesBtn="//button[@id='btnConfirmApproveBillerInfo']";
	public final static String Admin_SystemMgm_ApprovalCloseBtn="//button[text()='Close']";
	public final static String Admin_SystemMgm_RecordNotApproved="(//table[@id='dtBasicExample']//tbody/tr[@role='row'])";
	public final static String Admin_SystemMgm_ErrorMeesage="//div[@id='alert-error']";
	public final static String Admin_ApproveBillerMangm="//a[text()='Approved Billers Management']";
	public final static String Admin_RejectButton="//button[@id='btnReject']";
	public final static String Admin_RejectConfiMessage="//div[@id='modalRejectBillerInfo']//div[@class='modal-body text-center']/h6";
	public final static String Admin_RejectYesButton="//button[@id='btnConfirmRejectBillerInfo']";
	public final static String Admin_SystemMgm_RecordApproved="(//table[@id='dtApprovedBillers']//tbody/tr[@role='row'])";
	public final static String Admin_SystemMgm_RecordUnclickable="//input[@class='switch unclickable']";
	public final static String Admin_SystemMgm_RecordNotFound="//td[text()='No data available in table']";
	public final static String Admin_SystemMgm_CorpName="(//table[@id='dtBasicExample']//tbody/tr[@role='row'])//td[2]";
	public final static String Admin_SystemMgm_CorpType="(//table[@id='dtBasicExample']//tbody/tr[@role='row'])//td[4]";
	public final static String Admin_SystemMgm_EmailConf="(//table[@id='dtBasicExample']//tbody/tr[@role='row'])//label[1]";
	public final static String Admin_SystemMgm_EyeIcon="((//table[@id='dtBasicExample']//tbody/tr[@role='row'])//a)[4]";
	public final static String Admin_SystemMgm_EyeIconView="((//table[@id='dtApprovedBillers']//tbody/tr[@role='row'])[1]//a[@class='mx-1 action bg-accent'])[2]";
	public final static String Admin_ApproveMgn_ToggleBtn="(//table[@id='dtApprovedBillers']//tbody/tr[@role='row'])[1]//input[@class='switch']";
	public final static String Admin_ApprovedMgm_BillerName="(//table[@id='dtApprovedBillers']//tbody/tr[@role='row'])//td[2]";
	public final static String Admin_ApprovedMgm_BillerID="(//table[@id='dtApprovedBillers']//tbody/tr[@role='row'])//td[3]";
	public final static String Admin_ApprovedMgm_BillerType="(//table[@id='dtApprovedBillers']//tbody/tr[@role='row'])//td[4]";
	public final static String Admin_ApprovedMgm_EmailConf="(//table[@id='dtApprovedBillers']//tbody/tr[@role='row'])//label[1]";
	public final static String Admin_ApprovedMgm_EyeIcon="((//table[@id='dtApprovedBillers']//tbody/tr[@role='row'])//a)[4]";
	public final static String Admin_NotAppmMgm_IsTrackerBiller="(//input[@name='IsTrackedBiller'])[2]/preceding-sibling::input";
	public final static String Admin_NotAppmMgm_IsTrackerBillerYesbtn="(//button[@id='btnConfirmSetAsTrackedBiller'])";
	public final static String Admin_TrackerBillerMangm="//a[text()='Tracked Billers Management']";
	public final static String Admin_TrackerBillerMangm_Record="(//table[@id='dtApprovedBillers']//tbody/tr[@role='row'])";
	public final static String Admin_TrackerBillerMangm_CorpName="(//table[@id='dtApprovedBillers']//tbody/tr[@role='row'])//td[2]";
	public final static String Admin_TrackerBillerMangm_CorpType="(//table[@id='dtApprovedBillers']//tbody/tr[@role='row'])//td[4]";
	public final static String Admin_TrackerBillerMangm_Corpotype="(//table[@id='dtApprovedBillers']//tbody/tr[@role='row'])//td[5]";
	public final static String Admin_TrackerBillerMangm_EmailConf="(//table[@id='dtApprovedBillers']//tbody/tr[@role='row'])//label[1]";
	public final static String Admin_TrackerBillerMangm_EyeIcon="((//table[@id='dtApprovedBillers']//tbody/tr[@role='row'])//a)[4]";
	public final static String Admin_TrackerBillerMangm_ToggleBtn="(//table[@id='dtApprovedBillers']//tbody/tr[@role='row'])[1]//input[@class='switch']";
	public final static String Admin_TrackerBillerMangm_SelectNewSuper="//select[@id='NewSuperBillerId']";
	public final static String Admin_TrackerBillerMangm_IndiviClenteID="((//table[@id='dtApprovedBillers']//tbody/tr[@role='row'])[1]//a[contains(@href,'BillerClients')])[1]";
	public final static String Admin_TrackerBillerMangm_CopoClientID="((//table[@id='dtApprovedBillers']//tbody/tr[@role='row'])[1]//a[contains(@href,'BillerClients')])[2]";
	public final static String Admin_IndividualClient_RowCount="(//table[@id='tblBillerClients']//tbody/tr[@role='row'])";
	public final static String Admin_ExportBille_InvoiceID="(//table[@id='tblBillList']//tbody/tr[@role='row'])[1]//a";
	//public final static String Admin_ExportBille_InvoiceID="((//table[@id='tblBillList']//tbody/tr[@role='row'])[1]//td/a)[1]";
	public final static String Admin_MyBill_Button="//a[text()='My Bills']";
	public final static String Admin_MyBill_BillNumberField="//input[@id='txtBillNo']";
	public final static String Admin_MyBill_ViewButton="//button[@id='btnViewInvoice']";
	public final static String Admin_MyBill_InvalidNumber="//span[@id='BillNo-invalid']";
	public final static String Admin_MyBill_BillNumber="//label[contains(text(),'Bill Number')]/h6";
	public final static String Admin_MyBill_BillStatus="//label[contains(text(),'Invoice Status:')]/h6";
	public final static String Admin_MyBill_DetailsHeader="//h3[contains(text(),'Invoice Details')]";
	
	public final static String Biller_GroupMgm_Header="//h6[text()='Groups Management']";
	public final static String Biller_GroupMgm_SearchGrpName="//input[@id='groupName']";
	public final static String Biller_GroupMgm_SearchCode="//input[@name='Code']";
	public final static String Biller_GroupMgm_SearchButton="//button[text()='Search']";
	public final static String Biller_GroupMgm_AddGrpBtn="//button[@id='btnAddGroup']";
	public final static String Biller_AddGroupMgm_ArabicName="//input[@name='NameAr']";
	public final static String Biller_AddGroupMgm_Name="//input[@name='Name']";
	public final static String Biller_AddGroupMgm_Description="//input[@name='Description']";
	public final static String Biller_AddGroupMgm_GroupCode="//input[@name='GroupCode']";
	public final static String Biller_AddGroupMgm_AddBtn="//button[@id='btnAdd']";
	public final static String Biller_GroupMgm_UsersBtn="//button[@onclick='GroupUsers(this);']";
	public final static String Biller_GroupMgm_Userspopup="//h6[@id='exampleModalLongTitle']";
	public final static String Biller_SearchGroupMgm_GrpName="(//table[@id='tblGroups']//tbody/tr[@role='row'])[1]//td[1]/a";
	public final static String Biller_SearchGroupMgm_Code="(//table[@id='tblGroups']//tbody/tr[@role='row'])[1]//td[2]";
	public final static String Biller_UserManagement="//a[contains(@id,'lnkUserAccount2')]";
	public final static String Biller_GropManagment="(//a[text()='Groups Management'])[last()]";
	public final static String Biller_SearchGroupMgm_EditIcon="(//table[@id='tblGroups']//tbody/tr[@role='row'])[1]//td[3]/button[contains(@id,'btnUpdatePermission')]";
	public final static String Biller_EditGroup_Receivable="//input[@id='2Receivables']";
	public final static String Biller_EditGroup_UpdateBtn="//button[@id='btnUpdate']";
	public final static String Biller_SearchGroupMgm_DeleteBtn="(//table[@id='tblGroups']//tbody/tr[@role='row'])[1]//td[6]/a";
	public final static String Biller_SearchGroupMgm_YesDeleteBtn="//button[@id='btnConfirmDelete']";
	public final static String Biller_SearchGroupMgm_Nodata="//td[text()='No data available in table']";
	public final static String Biller_SearchGroupMgm_PermissuionPOp="//h6[@id='exampleModalLongTitle']";
	public final static String Biller_Userlist_groups="//div[@id='GroupsListDiv']//label[@class='custom-control-label']";
	
	public final static String Admin_TaxSearch ="//input[@id='TaxName']";
	public final static String Admin_taxTable ="//table[@id='tblTaxes']";

	public final static String Biller_UserList_UserName="(//table[@id='tblUsers']//tbody/tr[@role='row'])[1]//a/span";
	public final static String Biller_UserList_IsDeletChekckbox="//input[@id='Deleted']";
	public final static String Biller_Invoice_ComCustIDList="//select[@name='CompanyId']/following-sibling::span//span[@class='select2-selection__arrow']";
	public final static String Biller_Invoice_NextPrevLink="(//li[a[text()='Next']]/preceding-sibling::li)[last()]/a";
	public final static String Biller_ExportBille_InvoiceID="(//table[@id='tblBillList']//tbody/tr[@role='row'])[1]//a";
	public final static String Biller_Invoice_CustIDList="//select[@name='CustomerId']/following-sibling::span//span[@class='select2-selection__arrow']";
	public final static String Biller_Invoice_subIndividualRdv="//input[@id='rdSubbillerIndividual']";
	public final static String Biller_Invoice_Createandsave="//button[@id='btnCreateInvoice']";
	public final static String Biller_Invoice_installmentButton="//button[@id='btnCreateRepeatInvoice']";
	public final static String Biller_Invoice_SaveINSTALButton="//button[@id='btnUpdateBill']";
	public final static String Biller_Invoice_ExportinastallButton="//button[text()='Export']";
	public final static String Biller_Invoice_pymtEle="//h6[text()='Payments invoices']";

	//Client Module
	 public final static String Biller_nonapproved_Afteradd="(//div[@class='card-body table-responsive']//tbody/tr[@role='row'])";
	 public final static String AppBiller_Name="//td[2]";
	 public final static String Userlist_close="//button[text()='Close']";

//Biller ReceivablesPaidOutSideEddat
	 public final static String Biller_PaidOustSideEdaat="//h6[text()='Paid Outside EDAAT']";
	 public final static String Biller_PaidOustSideEdaat_link="//a[@id='lnkPayCashList2']";
	 public final static String Biller_Receivables_link="//a[@id='lnkReceipts2']";
	 public final static String Biller_Receivables_PaidOutside_Table="//div[@id='tblReceiptVouchers_wrapper']";

	 //BillerSubBillerIndividual
	 public final static String Biller_subBiller="//a[@id='lnkSubBillers2']";
	 public final static String Biller_subBiller_individual="//h6[text()='Individual Sub Billers']";
	 public final static String Biller_subBiller_individual_link="//a[@id='lnkSubBillersIndividualList2']";
	 public final static String Biller_subBiller_individual_grid="//div[@id='tblSubBillers_wrapper']";

	 //BillerSubBillerAddIndividual
	 public final static String Biller_AddsubBiller_btn="//button[text()=' Add Sub Billers+']";
	 public final static String Biller_AddsubBiller_name="//input[@id='IndividualNameAr']";
	 public final static String Biller_AddsubBiller_National="//input[@name='NationalId']";
	 public final static String Biller_AddsubBiller_IBAN="//input[@id='IBAN']";
	 public final static String Biller_AddsubBiller_Beneficiary="//input[@id='BeneficiaryName']";
	 public final static String Biller_AddsubBiller_Iban="//input[@id='IBANAttachment']";
	 public final static String Biller_AddsubBiller_Fees="//label[text()='Fees Deduction Based on Product']";
	 public final static String Biller_AddsubBiller_mbl="//input[@id='MobileNo']";
	 public final static String Biller_AddsubBiller_Email="//input[@id='Email']";
	 public final static String Biller_AddsubBiller_addbtn="//input[@id='btnAdd']";
	 public final static String Biller_AddsubBiller_addprod="//a[@id='btnNewProduct']";
	 public final static String Biller_AddsubBiller_prodname="//select[@id='ProductId']";
	 public final static String Biller_AddsubBiller_fixed="//input[@id='txtProductFixedValue']";
	 public final static String Biller_AddsubBiller_per="//input[@id='txtProductPercentage']";
	 public final static String Biller_AddsubBiller_prodiban="//input[@id='txtProductIBAN']";
	 public final static String Biller_AddsubBiller_prodbene="//input[@id='txtProductBeneficiaryName']";
	 public final static String Biller_AddsubBiller_prodatch="//input[@id='ProductIBANAttachment']";
	 public final static String Biller_AddsubBiller_prodaddbt="//button[text()='Add']";
	 public final static String Biller_AddsubBiller_verify="//table[@id='tblSubBillers']//tr//td[2]";
	 public final static String Biller_AddsubBiller_SeaName="//input[@id='Name']";
	 public final static String Biller_AddsubBiller_SeaNation="//input[@id='NationalId']";
	 public final static String Biller_AddsubBiller_Search="//button[text()='Search']";
	 public final static String Biller_AddsubBiller_check="//label[text()='Transfer Fees Deduction from Sub Biller Share']";
	 
//Biller Receivables My balance
	 public final static String Biller_Receivables_balance="//h6[text()='Search228']";
	 public final static String Biller_Rcv_balFromd="//input[@id='FromDate']";
	 public final static String Biller_Rcv_balFromyear="//select[ @title='Change the year']";
	 public final static String Biller_Rcv_balFromon="//select[@title='Change the month']"; 
	 public final static String Biller_Rcv_balTod="//input[@id='ToDate']";
	 public final static String Biller_Rcv_balToyear="//select[@title='Change the year']";
	 public final static String Biller_Rcv_balTomon="//select[@title='Change the month']";
	 public final static String Biller_Rcv_balancelink="//a[text()='Balance Details']";
	 
	 public final static String Biller_Rcv_balContract="//input[@id='InvoiceNumber']";
	 public final static String Biller_Rcv_balsubBiller="//select[@id='SubBillerType']";
	 public final static String Biller_Rcv_balsubBillername="//span[@id='select2-InterpriseSubBillerId-container'] ";
	 public final static String Biller_Rcv_balSearch="//button[@id='btnSearch']";
	 public final static String Biller_Rcv_balverifyContract="//table[@id=\"tblWallets\"]//tr[1]//td[3]";
	 
	//Biller login footer
	 public final static String Biller_loginverify="//h5[text()='Login']";
	 public final static String Biller_About_Edaat="//a[text()='About Edaat']";
	 public final static String Biller_About_verify="//img[@class='w-100 fit-contain img-en']";

//Admin Module

//My Bills Module

	public String get(String t) throws Exception {
		return (String) this.getClass().getField(t).get(this);

	}
//Biller login footer
	 public final static String Biller_loginverify="//h5[text()='Login']";
	 public final static String Biller_About_Edaat="//a[text()='About Edaat']";
	 public final static String Biller_About_verify="//img[@class='w-100 fit-contain img-en']";
}
